import { ThemeProvider } from "@/components/shared/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >

        <ClerkProvider afterSignInUrl={"/profile"} afterSignUpUrl={"/"} appearance={{
          baseTheme: dark,
        }} publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
